### ISSUE TITLE
Missing index.js

### ISSUE THREAD

**Issue by grempe** [stampery/msgpackrpc#1]
You reference the `index.js file as your main in`package.json`.  This file does not exist. Therefore this repository cannot work when referenced from an npm package.

https://github.com/stampery/msgpackrpc/blob/master/package.json#L5

See also:

https://github.com/stampery/node/issues/2

**Comment by aesedepece** [comment]
Oops what a fail.
Apparently it was dropped by 73709374b1d6203621da8e8b4ff531912f3ace3e.

Thanks for the heads-up!
